// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "ping", input: never, result: [string, string] } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "create_user", input: UserMsg, result: Session } | 
        { key: "login", input: UserMsg, result: Session } | 
        { key: "logout", input: never, result: null },
    subscriptions: never
};

export type Session = { id: string; sessionId: number[]; createdAt: string; userId: string }

export type UserMsg = { email: string; password: string }
